name: Build and Publish NuGet Package

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore src/EventSourcing.sln

    # Build the project with a dynamically assigned version
    - name: Build
      run: dotnet build src/EventSourcing.sln --configuration Release /p:Version=0.0.${{ github.run_number }}

    # Create the NuGet package
    - name: Create NuGet package
      run: dotnet pack src/EventSourcing/EventSourcing.csproj --configuration Release --output ./nuget /p:Version=0.0.${{ github.run_number }}

    - name: List nuget directory
      run: ls nuget

    # Publish the NuGet package to GitHub Packages
    - name: Publish NuGet package
      run: dotnet nuget push D:/a/EventSourcing.Base/EventSourcing.Base/nuget/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
